### ISSUE TITLE
I have some trouble in running the "eval_diversity_image.py"

### ISSUE THREAD

**Issue by laobameishijia** [Yuanyuan-Yuan/NeuraL-Coverage#1]
When i try to run the "eval_diversity_image.py" with "python eval_diversity_image.py --model resnet50 --dataset CIFAR10 --criterion NC ",  the error information is as follows. 

I guess it's because of memory limitations ?

```python
PS F:\xxxxx\xxxxx\xxxxx\xxxxx\xxxxx\NeuraL-Coverage> python eval_diversity_image.py --model resnet50 --dataset CIFAR10 --criterion NC 
--hyper 0.75
Dataset: CIFAR10     
Model: resnet50      
Criterion: NC        
Hyper-parameter: 0.75
Total 50000 Data.
Total 10000 Data.
Total 54 layers: 
Total 26570 neurons: 
Initial coverage: 0  
Dataset: CIFAR10     
Model: resnet50      
Criterion: NC        
Hyper-parameter: 0.75
Total 50000 Data.
Total 10000 Data.
Total 54 layers: 
Total 26570 neurons: 
Initial coverage: 0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\python3.8.10\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\python3.8.10\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "D:\python3.8.10\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\python3.8.10\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "D:\python3.8.10\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "D:\python3.8.10\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "D:\python3.8.10\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "F:\xxxxx\xxxxx\xxxxx\xxxxx\xxxxx\NeuraL-Coverage\eval_diversity_image.py", line 99, in <module>
    for i, (old_image, label) in enumerate(seed_loader):
  File "D:\python3.8.10\lib\site-packages\torch\utils\data\dataloader.py", line 441, in __iter__
    return self._get_iterator()
  File "D:\python3.8.10\lib\site-packages\torch\utils\data\dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "D:\python3.8.10\lib\site-packages\torch\utils\data\dataloader.py", line 1042, in __init__
    w.start()
  File "D:\python3.8.10\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "D:\python3.8.10\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\python3.8.10\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "D:\python3.8.10\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "D:\python3.8.10\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "D:\python3.8.10\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

```

**Comment by laobameishijia** [comment]
I was so anxious to ask the question that I didn't think much. Maybe you just need to add the ` if __name__ == '__main__':
    freeze_support() ` statement to run successfully

**Comment by ooorin** [comment]
Hi @laobameishijia ,

Can you provide more information on how you run the script? I cannot reproduce the error and everything goes well on my end.

Best,
Yuanyuan

**Comment by laobameishijia** [comment]
Hi @ooorin .Sorry for I didn't see it until now. 
I'm not sure why, but `if __name__ == '__main__': freeze_support()` is added according to the error message, and it works. I use Python 3.8.10 && Windows10 && Vscode.  I guess may be the reason for using `tqdm`.
