### ISSUE TITLE
I have some trouble in installation packages. 

### ISSUE THREAD

**Issue by yeseuly** [Yuanyuan-Yuan/NeuraL-Coverage#2]
_ **I use the Docker environment
and I made the dockerfile as belows:**_

```shell
FROM python:3.9

RUN pip install --upgrade pip
RUN pip install opencv-python==4.5.3.56
RUN pip install torchtext==0.11.0 torch==1.10.0 torchvision==0.1.6 scipy==1.7.3 scikit-learn==1.0.2 pillow six pyflann-py3

COPY . /NeuraL-Coverage

ENV HOME /NeuraL-Coverage
RUN env

WORKDIR $HOME
CMD ["bash"]
``` 

_**I have an error as shown belows:**_

```python
Traceback (most recent call last):
  File "/NeuraL-Coverage/eval_diversity_image.py", line 17, in <module>
    import coverage
  File "/NeuraL-Coverage/coverage.py", line 8, in <module>
    from pyflann import FLANN
  File "/usr/local/lib/python3.9/site-packages/pyflann/__init__.py", line 27, in <module>
    from .index import *
  File "/usr/local/lib/python3.9/site-packages/pyflann/index.py", line 27, in <module>
    from .bindings.flann_ctypes import *
  File "/usr/local/lib/python3.9/site-packages/pyflann/bindings/__init__.py", line 30, in <module>
    from .flann_ctypes import *
  File "/usr/local/lib/python3.9/site-packages/pyflann/bindings/flann_ctypes.py", line 173, in <module>
    raise ImportError('Cannot load dynamic library. Did you compile FLANN?')
ImportError: Cannot load dynamic library. Did you compile FLANN?
```

**Comment by ooorin** [comment]
Hi @yeseuly ,

I tried to re-install `pyflann-py3` and everything works smoothly on my machine. I found an issue comment in the official flann project that might be helpful for you: https://github.com/flann-lib/flann/issues/281#issuecomment-207177652

BTW, if you cannot fix this problem, you can just delete the import because pyflann is only used for cluster-based coverage (CC) to approximate nearest neighbors. I use pyflann because this package is mentioned in CC's paper (https://arxiv.org/pdf/1807.10875.pdf).

Best,
Yuanyuan
